name = "cloudflare-worker-bot"
main = "worker.js"
compatibility_date = "2024-12-19"

[build.upload]
format = "modules"

# Environment variables (optional)
# [vars]
# ENVIRONMENT = "production"

# KV Namespaces (optional)
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "your-kv-namespace-id"

# Durable Objects (optional)
# [[durable_objects.bindings]]
# name = "MY_DURABLE_OBJECT"
# class_name = "MyDurableObject"

# R2 Buckets (optional)
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# Worker Routes (optional)
# [[routes]]
# pattern = "example.com/*"
# zone_name = "example.com"